export class Categories {
  constructor() {}
  getConstant() {
    return {
      per_page: 104,
      page: 1,
      total_entries: 104,
      categories: [
        {
          name: 'Concerts',
          id: '54',
          slug: 'concerts',
          url: '/categories/54',
          slug_url: '/categories/concerts',
          updated_at: '2014-05-08T16:01:57Z',
          parent: null,
        },
        {
          name: 'Comedy',
          id: '55',
          slug: 'comedy',
          url: '/categories/55',
          slug_url: '/categories/comedy',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Family',
          id: '56',
          slug: 'family',
          url: '/categories/56',
          slug_url: '/categories/family',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Alternative & Indie',
          id: '58',
          slug: 'alternative-indie',
          url: '/categories/58',
          slug_url: '/categories/alternative-indie',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'R&B/Urban Soul',
          id: '60',
          slug: 'r-b-urban-soul',
          url: '/categories/60',
          slug_url: '/categories/r-b-urban-soul',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Country & Folk',
          id: '61',
          slug: 'country-folk',
          url: '/categories/61',
          slug_url: '/categories/country-folk',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Jazz & Blues',
          id: '62',
          slug: 'jazz-blues',
          url: '/categories/62',
          slug_url: '/categories/jazz-blues',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Festivals',
          id: '63',
          slug: 'festivals',
          url: '/categories/63',
          slug_url: '/categories/festivals',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'World Music',
          id: '65',
          slug: 'world-music',
          url: '/categories/65',
          slug_url: '/categories/world-music',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Classical',
          id: '67',
          slug: 'classical',
          url: '/categories/67',
          slug_url: '/categories/classical',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Alternative Rock',
          id: '82',
          slug: 'alternative-rock',
          url: '/categories/82',
          slug_url: '/categories/alternative-rock',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Cabaret',
          id: '83',
          slug: 'cabaret',
          url: '/categories/83',
          slug_url: '/categories/cabaret',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Latin',
          id: '85',
          slug: 'latin',
          url: '/categories/85',
          slug_url: '/categories/latin',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'New Age & Spiritual',
          id: '86',
          slug: 'new-age-spiritual',
          url: '/categories/86',
          slug_url: '/categories/new-age-spiritual',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Rap & Hip-Hop',
          id: '59',
          slug: 'rap-hip-hop',
          url: '/categories/59',
          slug_url: '/categories/rap-hip-hop',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Rock & Pop',
          id: '57',
          slug: 'rock-pop',
          url: '/categories/57',
          slug_url: '/categories/rock-pop',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Miscellaneous',
          id: '87',
          slug: 'miscellaneous',
          url: '/categories/87',
          slug_url: '/categories/miscellaneous',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Theatre',
          id: '68',
          slug: 'theatre',
          url: '/categories/68',
          slug_url: '/categories/theatre',
          updated_at: '2014-05-08T16:01:58Z',
          parent: null,
        },
        {
          name: 'Musicals',
          id: '69',
          slug: 'musicals',
          url: '/categories/69',
          slug_url: '/categories/musicals',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Theatre',
            id: '68',
            slug: 'theatre',
            url: '/categories/68',
            slug_url: '/categories/theatre',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'Plays',
          id: '70',
          slug: 'plays',
          url: '/categories/70',
          slug_url: '/categories/plays',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Theatre',
            id: '68',
            slug: 'theatre',
            url: '/categories/68',
            slug_url: '/categories/theatre',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'Opera',
          id: '71',
          slug: 'opera',
          url: '/categories/71',
          slug_url: '/categories/opera',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Theatre',
            id: '68',
            slug: 'theatre',
            url: '/categories/68',
            slug_url: '/categories/theatre',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'Ballet & Dance',
          id: '72',
          slug: 'ballet-dance',
          url: '/categories/72',
          slug_url: '/categories/ballet-dance',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Theatre',
            id: '68',
            slug: 'theatre',
            url: '/categories/68',
            slug_url: '/categories/theatre',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'Special Events',
          id: '73',
          slug: 'special-events',
          url: '/categories/73',
          slug_url: '/categories/special-events',
          updated_at: '2014-05-08T16:01:58Z',
          parent: null,
        },
        {
          name: 'Award Shows',
          id: '74',
          slug: 'award-shows',
          url: '/categories/74',
          slug_url: '/categories/award-shows',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Special Events',
            id: '73',
            slug: 'special-events',
            url: '/categories/73',
            slug_url: '/categories/special-events',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'TV Shows',
          id: '75',
          slug: 'tv-shows',
          url: '/categories/75',
          slug_url: '/categories/tv-shows',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Special Events',
            id: '73',
            slug: 'special-events',
            url: '/categories/73',
            slug_url: '/categories/special-events',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'Fundraisers',
          id: '76',
          slug: 'fundraisers',
          url: '/categories/76',
          slug_url: '/categories/fundraisers',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Special Events',
            id: '73',
            slug: 'special-events',
            url: '/categories/73',
            slug_url: '/categories/special-events',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'Minor League',
          id: '4',
          slug: 'minor-league',
          url: '/categories/4',
          slug_url: '/categories/minor-league',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Baseball',
            id: '2',
            slug: 'baseball',
            url: '/categories/2',
            slug_url: '/categories/baseball',
            updated_at: '2014-05-08T16:01:55Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'NCAA',
          id: '5',
          slug: 'ncaa',
          url: '/categories/5',
          slug_url: '/categories/ncaa',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Baseball',
            id: '2',
            slug: 'baseball',
            url: '/categories/2',
            slug_url: '/categories/baseball',
            updated_at: '2014-05-08T16:01:55Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Sports',
          id: '1',
          slug: 'sports',
          url: '/categories/1',
          slug_url: '/categories/sports',
          updated_at: '2014-05-08T16:01:55Z',
          parent: null,
        },
        {
          name: 'Lacrosse',
          id: '78',
          slug: 'lacrosse',
          url: '/categories/78',
          slug_url: '/categories/lacrosse',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'NCAA Men',
          id: '79',
          slug: 'ncaa-men',
          url: '/categories/79',
          slug_url: '/categories/ncaa-men',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Lacrosse',
            id: '78',
            slug: 'lacrosse',
            url: '/categories/78',
            slug_url: '/categories/lacrosse',
            updated_at: '2014-05-08T16:01:55Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Summer Games',
          id: '52',
          slug: 'summer-games',
          url: '/categories/52',
          slug_url: '/categories/summer-games',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'International Games',
            id: '51',
            slug: 'international-games',
            url: '/categories/51',
            slug_url: '/categories/international-games',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Baseball',
          id: '2',
          slug: 'baseball',
          url: '/categories/2',
          slug_url: '/categories/baseball',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'MLB',
          id: '3',
          slug: 'mlb',
          url: '/categories/3',
          slug_url: '/categories/mlb',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Baseball',
            id: '2',
            slug: 'baseball',
            url: '/categories/2',
            slug_url: '/categories/baseball',
            updated_at: '2014-05-08T16:01:55Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Basketball',
          id: '7',
          slug: 'basketball',
          url: '/categories/7',
          slug_url: '/categories/basketball',
          updated_at: '2014-05-08T16:01:56Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'NBA',
          id: '8',
          slug: 'nba',
          url: '/categories/8',
          slug_url: '/categories/nba',
          updated_at: '2014-05-08T16:01:56Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'WNBA',
          id: '9',
          slug: 'wnba',
          url: '/categories/9',
          slug_url: '/categories/wnba',
          updated_at: '2014-05-08T16:01:56Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'NCAA Men',
          id: '10',
          slug: 'ncaa-men--2',
          url: '/categories/10',
          slug_url: '/categories/ncaa-men--2',
          updated_at: '2014-05-08T16:01:56Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'NCAA Women',
          id: '11',
          slug: 'ncaa-women',
          url: '/categories/11',
          slug_url: '/categories/ncaa-women',
          updated_at: '2014-05-08T16:01:56Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'FIBA World Championship',
          id: '12',
          slug: 'fiba-world-championship',
          url: '/categories/12',
          slug_url: '/categories/fiba-world-championship',
          updated_at: '2014-05-08T16:01:56Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Euroleague Basketball',
          id: '13',
          slug: 'euroleague-basketball',
          url: '/categories/13',
          slug_url: '/categories/euroleague-basketball',
          updated_at: '2014-05-08T16:01:56Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Hockey',
          id: '15',
          slug: 'hockey',
          url: '/categories/15',
          slug_url: '/categories/hockey',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'NCAA Men',
          id: '17',
          slug: 'ncaa-men--3',
          url: '/categories/17',
          slug_url: '/categories/ncaa-men--3',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Hockey',
            id: '15',
            slug: 'hockey',
            url: '/categories/15',
            slug_url: '/categories/hockey',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'IndyCar Series',
          id: '30',
          slug: 'indycar-series',
          url: '/categories/30',
          slug_url: '/categories/indycar-series',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Auto Racing',
            id: '27',
            slug: 'auto-racing',
            url: '/categories/27',
            slug_url: '/categories/auto-racing',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Monster Trucks',
          id: '31',
          slug: 'monster-trucks',
          url: '/categories/31',
          slug_url: '/categories/monster-trucks',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Auto Racing',
            id: '27',
            slug: 'auto-racing',
            url: '/categories/27',
            slug_url: '/categories/auto-racing',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'NASCAR',
          id: '28',
          slug: 'nascar',
          url: '/categories/28',
          slug_url: '/categories/nascar',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Auto Racing',
            id: '27',
            slug: 'auto-racing',
            url: '/categories/27',
            slug_url: '/categories/auto-racing',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Supercross',
          id: '32',
          slug: 'supercross',
          url: '/categories/32',
          slug_url: '/categories/supercross',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Auto Racing',
            id: '27',
            slug: 'auto-racing',
            url: '/categories/27',
            slug_url: '/categories/auto-racing',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Boxing',
          id: '47',
          slug: 'boxing',
          url: '/categories/47',
          slug_url: '/categories/boxing',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Fighting',
            id: '44',
            slug: 'fighting',
            url: '/categories/44',
            slug_url: '/categories/fighting',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Wrestling',
          id: '45',
          slug: 'wrestling',
          url: '/categories/45',
          slug_url: '/categories/wrestling',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Fighting',
            id: '44',
            slug: 'fighting',
            url: '/categories/44',
            slug_url: '/categories/fighting',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Auto Racing',
          id: '27',
          slug: 'auto-racing',
          url: '/categories/27',
          slug_url: '/categories/auto-racing',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'Extreme Sports',
          id: '49',
          slug: 'extreme-sports',
          url: '/categories/49',
          slug_url: '/categories/extreme-sports',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'Fighting',
          id: '44',
          slug: 'fighting',
          url: '/categories/44',
          slug_url: '/categories/fighting',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'NLL',
          id: '80',
          slug: 'nll',
          url: '/categories/80',
          slug_url: '/categories/nll',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Lacrosse',
            id: '78',
            slug: 'lacrosse',
            url: '/categories/78',
            slug_url: '/categories/lacrosse',
            updated_at: '2014-05-08T16:01:55Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Golf',
          id: '24',
          slug: 'golf',
          url: '/categories/24',
          slug_url: '/categories/golf',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'NCAA Women',
          id: '18',
          slug: 'ncaa-women--2',
          url: '/categories/18',
          slug_url: '/categories/ncaa-women--2',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Hockey',
            id: '15',
            slug: 'hockey',
            url: '/categories/15',
            slug_url: '/categories/hockey',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'NHL',
          id: '16',
          slug: 'nhl',
          url: '/categories/16',
          slug_url: '/categories/nhl',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Hockey',
            id: '15',
            slug: 'hockey',
            url: '/categories/15',
            slug_url: '/categories/hockey',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Football',
          id: '19',
          slug: 'football',
          url: '/categories/19',
          slug_url: '/categories/football',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'NFL',
          id: '20',
          slug: 'nfl',
          url: '/categories/20',
          slug_url: '/categories/nfl',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Football',
            id: '19',
            slug: 'football',
            url: '/categories/19',
            slug_url: '/categories/football',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'CFL',
          id: '22',
          slug: 'cfl',
          url: '/categories/22',
          slug_url: '/categories/cfl',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Football',
            id: '19',
            slug: 'football',
            url: '/categories/19',
            slug_url: '/categories/football',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'UFL',
          id: '23',
          slug: 'ufl',
          url: '/categories/23',
          slug_url: '/categories/ufl',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Football',
            id: '19',
            slug: 'football',
            url: '/categories/19',
            slug_url: '/categories/football',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Soccer',
          id: '34',
          slug: 'soccer',
          url: '/categories/34',
          slug_url: '/categories/soccer',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'MLS (Major League Soccer)',
          id: '36',
          slug: 'mls-major-league-soccer',
          url: '/categories/36',
          slug_url: '/categories/mls-major-league-soccer',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'English Premiere League',
          id: '37',
          slug: 'english-premiere-league',
          url: '/categories/37',
          slug_url: '/categories/english-premiere-league',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Confederação Brasileira de Futebol',
          id: '39',
          slug: 'confederacao-brasileira-de-futebol',
          url: '/categories/39',
          slug_url: '/categories/confederacao-brasileira-de-futebol',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Bundesliga',
          id: '40',
          slug: 'bundesliga',
          url: '/categories/40',
          slug_url: '/categories/bundesliga',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Spanish Primera División',
          id: '41',
          slug: 'spanish-primera-division',
          url: '/categories/41',
          slug_url: '/categories/spanish-primera-division',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Italian Serie A',
          id: '42',
          slug: 'italian-serie-a',
          url: '/categories/42',
          slug_url: '/categories/italian-serie-a',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Ligat HaAl',
          id: '43',
          slug: 'ligat-haal',
          url: '/categories/43',
          slug_url: '/categories/ligat-haal',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Rugby',
          id: '48',
          slug: 'rugby',
          url: '/categories/48',
          slug_url: '/categories/rugby',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'X-Games',
          id: '50',
          slug: 'x-games',
          url: '/categories/50',
          slug_url: '/categories/x-games',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Extreme Sports',
            id: '49',
            slug: 'extreme-sports',
            url: '/categories/49',
            slug_url: '/categories/extreme-sports',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Rodeo',
          id: '26',
          slug: 'rodeo',
          url: '/categories/26',
          slug_url: '/categories/rodeo',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'Tennis',
          id: '25',
          slug: 'tennis',
          url: '/categories/25',
          slug_url: '/categories/tennis',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'NCAA',
          id: '21',
          slug: 'ncaa--2',
          url: '/categories/21',
          slug_url: '/categories/ncaa--2',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Football',
            id: '19',
            slug: 'football',
            url: '/categories/19',
            slug_url: '/categories/football',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Formula 1',
          id: '29',
          slug: 'formula-1',
          url: '/categories/29',
          slug_url: '/categories/formula-1',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Auto Racing',
            id: '27',
            slug: 'auto-racing',
            url: '/categories/27',
            slug_url: '/categories/auto-racing',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Winter Games',
          id: '53',
          slug: 'winter-games',
          url: '/categories/53',
          slug_url: '/categories/winter-games',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'International Games',
            id: '51',
            slug: 'international-games',
            url: '/categories/51',
            slug_url: '/categories/international-games',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Mexican League',
          id: '121',
          slug: 'mexican-league',
          url: '/categories/121',
          slug_url: '/categories/mexican-league',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Baseball',
            id: '2',
            slug: 'baseball',
            url: '/categories/2',
            slug_url: '/categories/baseball',
            updated_at: '2014-05-08T16:01:55Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'NBA D-League',
          id: '122',
          slug: 'nba-d-league',
          url: '/categories/122',
          slug_url: '/categories/nba-d-league',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Lingerie Football League',
          id: '123',
          slug: 'lingerie-football-league',
          url: '/categories/123',
          slug_url: '/categories/lingerie-football-league',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Football',
            id: '19',
            slug: 'football',
            url: '/categories/19',
            slug_url: '/categories/football',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'High School',
          id: '129',
          slug: 'high-school',
          url: '/categories/129',
          slug_url: '/categories/high-school',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Cycling',
          id: '125',
          slug: 'cycling',
          url: '/categories/125',
          slug_url: '/categories/cycling',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'AHL',
          id: '126',
          slug: 'ahl',
          url: '/categories/126',
          slug_url: '/categories/ahl',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Hockey',
            id: '15',
            slug: 'hockey',
            url: '/categories/15',
            slug_url: '/categories/hockey',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'ECHL',
          id: '127',
          slug: 'echl',
          url: '/categories/127',
          slug_url: '/categories/echl',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Hockey',
            id: '15',
            slug: 'hockey',
            url: '/categories/15',
            slug_url: '/categories/hockey',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Volleyball',
          id: '128',
          slug: 'volleyball',
          url: '/categories/128',
          slug_url: '/categories/volleyball',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'AFL',
          id: '81',
          slug: 'afl',
          url: '/categories/81',
          slug_url: '/categories/afl',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Football',
            id: '19',
            slug: 'football',
            url: '/categories/19',
            slug_url: '/categories/football',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'World Baseball Classic',
          id: '6',
          slug: 'world-baseball-classic',
          url: '/categories/6',
          slug_url: '/categories/world-baseball-classic',
          updated_at: '2014-05-08T16:01:55Z',
          parent: {
            name: 'Baseball',
            id: '2',
            slug: 'baseball',
            url: '/categories/2',
            slug_url: '/categories/baseball',
            updated_at: '2014-05-08T16:01:55Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'International Friendlies',
          id: '14',
          slug: 'international-friendlies',
          url: '/categories/14',
          slug_url: '/categories/international-friendlies',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Basketball',
            id: '7',
            slug: 'basketball',
            url: '/categories/7',
            slug_url: '/categories/basketball',
            updated_at: '2014-05-08T16:01:56Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Mixed Martial Arts (MMA)',
          id: '46',
          slug: 'mixed-martial-arts-mma',
          url: '/categories/46',
          slug_url: '/categories/mixed-martial-arts-mma',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Fighting',
            id: '44',
            slug: 'fighting',
            url: '/categories/44',
            slug_url: '/categories/fighting',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'NCAA Men',
          id: '88',
          slug: 'ncaa-men--4',
          url: '/categories/88',
          slug_url: '/categories/ncaa-men--4',
          updated_at: '2014-05-08T16:01:57Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'World Cup',
          id: '35',
          slug: 'world-cup',
          url: '/categories/35',
          slug_url: '/categories/world-cup',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Scottish Premiere League',
          id: '38',
          slug: 'scottish-premiere-league',
          url: '/categories/38',
          slug_url: '/categories/scottish-premiere-league',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Horse Racing',
          id: '33',
          slug: 'horse-racing',
          url: '/categories/33',
          slug_url: '/categories/horse-racing',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'International Games',
          id: '51',
          slug: 'international-games',
          url: '/categories/51',
          slug_url: '/categories/international-games',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Sports',
            id: '1',
            slug: 'sports',
            url: '/categories/1',
            slug_url: '/categories/sports',
            updated_at: '2014-05-08T16:01:55Z',
            parent: null,
          },
        },
        {
          name: 'Hard Rock/Metal',
          id: '64',
          slug: 'hard-rock-metal',
          url: '/categories/64',
          slug_url: '/categories/hard-rock-metal',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Dance/Electronic',
          id: '84',
          slug: 'dance-electronic',
          url: '/categories/84',
          slug_url: '/categories/dance-electronic',
          updated_at: '2014-05-08T16:01:59Z',
          parent: {
            name: 'Concerts',
            id: '54',
            slug: 'concerts',
            url: '/categories/54',
            slug_url: '/categories/concerts',
            updated_at: '2014-05-08T16:01:57Z',
            parent: null,
          },
        },
        {
          name: 'Exclusive Parties',
          id: '77',
          slug: 'exclusive-parties',
          url: '/categories/77',
          slug_url: '/categories/exclusive-parties',
          updated_at: '2014-05-08T16:01:58Z',
          parent: {
            name: 'Special Events',
            id: '73',
            slug: 'special-events',
            url: '/categories/73',
            slug_url: '/categories/special-events',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
        {
          name: 'NCAA Women',
          id: '130',
          slug: 'ncaa-women--3',
          url: '/categories/130',
          slug_url: '/categories/ncaa-women--3',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Soccer',
            id: '34',
            slug: 'soccer',
            url: '/categories/34',
            slug_url: '/categories/soccer',
            updated_at: '2014-05-08T16:01:59Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'PGA',
          id: '131',
          slug: 'pga',
          url: '/categories/131',
          slug_url: '/categories/pga',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Golf',
            id: '24',
            slug: 'golf',
            url: '/categories/24',
            slug_url: '/categories/golf',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Champions',
          id: '132',
          slug: 'champions',
          url: '/categories/132',
          slug_url: '/categories/champions',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Golf',
            id: '24',
            slug: 'golf',
            url: '/categories/24',
            slug_url: '/categories/golf',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'LPGA',
          id: '133',
          slug: 'lpga',
          url: '/categories/133',
          slug_url: '/categories/lpga',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Golf',
            id: '24',
            slug: 'golf',
            url: '/categories/24',
            slug_url: '/categories/golf',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'European',
          id: '134',
          slug: 'european',
          url: '/categories/134',
          slug_url: '/categories/european',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Golf',
            id: '24',
            slug: 'golf',
            url: '/categories/24',
            slug_url: '/categories/golf',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Amateur',
          id: '135',
          slug: 'amateur',
          url: '/categories/135',
          slug_url: '/categories/amateur',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Golf',
            id: '24',
            slug: 'golf',
            url: '/categories/24',
            slug_url: '/categories/golf',
            updated_at: '2014-05-08T16:01:58Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Junior',
          id: '136',
          slug: 'junior',
          url: '/categories/136',
          slug_url: '/categories/junior',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Hockey',
            id: '15',
            slug: 'hockey',
            url: '/categories/15',
            slug_url: '/categories/hockey',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'International',
          id: '137',
          slug: 'international',
          url: '/categories/137',
          slug_url: '/categories/international',
          updated_at: '2014-05-08T16:02:00Z',
          parent: {
            name: 'Hockey',
            id: '15',
            slug: 'hockey',
            url: '/categories/15',
            slug_url: '/categories/hockey',
            updated_at: '2014-05-08T16:01:57Z',
            parent: {
              name: 'Sports',
              id: '1',
              slug: 'sports',
              url: '/categories/1',
              slug_url: '/categories/sports',
              updated_at: '2014-05-08T16:01:55Z',
              parent: null,
            },
          },
        },
        {
          name: 'Entertainment Shows',
          id: '138',
          slug: 'entertainment-shows',
          url: '/categories/138',
          slug_url: '/categories/entertainment-shows',
          updated_at: '2018-04-27T18:13:44Z',
          parent: {
            name: 'Theatre',
            id: '68',
            slug: 'theatre',
            url: '/categories/68',
            slug_url: '/categories/theatre',
            updated_at: '2014-05-08T16:01:58Z',
            parent: null,
          },
        },
      ],
    };
  }
}
